export const config = {
  expression_complex_level: 1,
  debug: false,
  tuple_prob: 0.3,
  var_count: 5,
  tuple_vardecl_count: 3,
  maximum_type_resolution_for_heads: 50000,
  literal_prob: 0.3,
  function_count: 2,
  param_count_of_function_upperlimit: 3,
  return_count_of_function_upperlimit: 3,
  stmt_count_of_function_upperlimit: 5,
  uint_num: 6,
  int_num: 6,
  unit_test_mode: false,
}