export const config = {
  expression_complex_level: 3,
  debug: false,
  tuple_prob: 0.3,
  maximum_type_resolution_for_heads: 2000000,
  literal_prob: 0.3,
  function_count_per_contract: 2,
  param_count_of_function_upperlimit: 1,
  param_count_of_function_lowerlimit: 0,
  return_count_of_function_upperlimit: 2,
  return_count_of_function_lowerlimit: 0,
  body_stmt_count_of_function_upperlimit: 2,
  body_stmt_count_of_function_lowerlimit: 0,
  state_variable_count_upperlimit: 2,
  state_variable_count_lowerlimit: 1,
  uint_num: 2,
  int_num: 2,
  unit_test_mode: false,
  chunk_size: 100000,
  experimental: false,
  contract_count: 2,
  file: "",
  out_dir: "",
  no_type_exploration: false,
  mode: "type",
  vardecl_prob: 0.2,
  else_prob: 0.3
}